"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clipboard, Download, Loader2, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { useParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { api } from "@/lib/api";

const input = "h-10 w-full border border-terminal-line bg-terminal-bg px-3 text-sm";
const button = "inline-flex h-9 items-center gap-2 border border-terminal-green/60 bg-terminal-green/10 px-3 text-sm text-terminal-green disabled:opacity-50";

export default function ValidationDetailPage() {
  const id = String(useParams().id); const client = useQueryClient();
  const query = useQuery({ queryKey: ["validation-project", id], queryFn: () => api.validationProject(id) });
  const reload = () => client.invalidateQueries({ queryKey: ["validation-project", id] });
  const action = useMutation({ mutationFn: ({name, data}: {name: string; data?: string}) => name === "refresh" ? api.refreshValidationPacket(id) : name === "rfq" ? api.generateRfq(id) : name === "gates" ? api.evaluateValidationGates(id) : api.transitionValidation(id, name, data ?? "Manual validation transition"), onSuccess: reload });
  const project = query.data; const packet = project?.marketplace_packets?.[0]; const rfq = project?.rfqs?.[0];
  if (query.isLoading) return <p className="text-sm text-terminal-muted">Loading validation...</p>;
  if (!project) return <p className="text-terminal-rose">Validation project unavailable.</p>;
  return <div className="space-y-6">
    <header className="border-b border-terminal-line pb-5"><div className="font-mono text-xs uppercase text-terminal-green">Validation / {project.status.replaceAll("_", " ")}</div><h1 className="mt-2 text-2xl font-semibold">{project.title}</h1><div className="mt-4 flex flex-wrap gap-2"><Action busy={action.isPending} onClick={() => action.mutate({name:"refresh"})} icon={<RefreshCw size={14}/>} label="Refresh marketplace evidence"/><Action busy={action.isPending} onClick={() => action.mutate({name:"gates"})} icon={<ShieldCheck size={14}/>} label="Evaluate gates"/><TransitionButtons status={project.status} run={(name) => action.mutate({name})}/></div>{action.error ? <p className="mt-2 text-sm text-terminal-rose">{action.error.message}</p> : null}</header>
    <Section title="01 / Overview"><div className="grid gap-4 sm:grid-cols-4"><Metric label="Opportunity" value={num(project.latest_opportunity_score)}/><Metric label="Confidence" value={num(project.confidence_score)}/><Metric label="Max landed cost" value={cash(project.max_landed_cost)}/><Metric label="Decision readiness" value={project.decision_readiness.replaceAll("_", " ")}/></div></Section>
    <Section title="02 / Marketplace evidence">{packet ? <><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-6"><Metric label="Packet" value={`v${packet.version}`}/><Metric label="Sale price" value={cash(packet.expected_sale_price)}/><Metric label="Amazon fees" value={cash(packet.amazon_fees_per_unit)}/><Metric label="Cost ceiling" value={cash(packet.max_landed_cost)}/><Metric label="Comparables" value={String(packet.effective_comparable_count)}/><Metric label="Observed" value={new Date(packet.observed_at).toLocaleDateString()}/></div><EvidenceList title="Missing" values={packet.missing_evidence}/><EvidenceList title="Conflicting" values={packet.conflicting_evidence}/></> : <p className="text-sm text-terminal-muted">No marketplace packet.</p>}</Section>
    <PoeForm id={id} initial={project.poe_evidence} onSaved={reload}/>
    <Section title="04 / RFQ"><div className="mb-3 flex flex-wrap gap-2"><button className={button} onClick={() => action.mutate({name:"rfq"})}><Plus size={14}/>Generate revision</button>{rfq ? <><button className={button} onClick={() => navigator.clipboard.writeText(rfq.rendered_markdown)}><Clipboard size={14}/>Copy</button><DownloadButton rfq={rfq} extension="md"/><DownloadButton rfq={rfq} extension="txt"/></> : null}</div>{rfq ? <textarea readOnly value={rfq.rendered_markdown} className="min-h-72 w-full border border-terminal-line bg-terminal-bg p-3 font-mono text-xs leading-5"/> : <p className="text-sm text-terminal-muted">Generate an RFQ when marketplace evidence is ready.</p>}</Section>
    <QuoteSection id={id} quotes={project.quotes ?? []} onSaved={reload}/>
    <Section title="06 / Economics"><QuoteTable quotes={project.quotes ?? []}/></Section>
    <Section title="07 / Risks"><p className="text-sm text-terminal-muted">Risk readiness is evaluated through the existing constraint engine and shown in the gates below.</p></Section>
    <Section title="08 / Decision gates"><div className="grid gap-3 md:grid-cols-2">{["marketplace","sourcing","economics","risk","decision_readiness"].map(name => {const gate=project.gates?.[name]; return <div key={name} className="border border-terminal-line p-3"><div className="flex justify-between"><strong className="capitalize">{name.replaceAll("_"," ")}</strong><span className={gate?.status === "passed" ? "text-terminal-green" : gate?.status === "failed" ? "text-terminal-rose" : "text-terminal-amber"}>{gate?.status ?? "not evaluated"}</span></div><p className="mt-2 text-sm text-terminal-muted">{gate?.summary ?? "Run gate evaluation."}</p>{gate?.missing_inputs?.length ? <p className="mt-2 text-xs">Next: {gate.missing_inputs.join(", ")}</p>:null}</div>})}</div></Section>
    <Section title="09 / Audit history">{project.audit_history?.length ? project.audit_history.map((row, i) => <div key={i} className="border-b border-terminal-line py-2 text-sm">{String(row.from_status)} → {String(row.to_status)} <span className="text-terminal-muted">{String(row.reason)} / {new Date(String(row.timestamp)).toLocaleString()}</span></div>) : <p className="text-sm text-terminal-muted">No transitions recorded yet.</p>}</Section>
  </div>;
}

function Section({title, children}:{title:string;children:React.ReactNode}) { return <section className="border border-terminal-line bg-terminal-panel/50"><h2 className="border-b border-terminal-line px-4 py-3 font-mono text-xs uppercase text-terminal-muted">{title}</h2><div className="p-4">{children}</div></section> }
function Metric({label,value}:{label:string;value:string}) { return <div><div className="font-mono text-xs uppercase text-terminal-muted">{label}</div><div className="mt-1 text-lg">{value}</div></div> }
function Action({busy,onClick,icon,label}:{busy:boolean;onClick:()=>void;icon:React.ReactNode;label:string}) { return <button disabled={busy} onClick={onClick} className={button}>{busy?<Loader2 size={14} className="animate-spin"/>:icon}{label}</button> }
function TransitionButtons({status,run}:{status:string;run:(s:string)=>void}) { const options:Record<string,string[]>={draft:["marketplace_validation"],marketplace_validation:["sourcing","rejected"],sourcing:["ready_for_decision","rejected"],ready_for_decision:["approved_for_sample","sourcing","rejected"],approved_for_sample:["archived"],rejected:["marketplace_validation","archived"]}; return <>{(options[status]??[]).map(s=><button key={s} onClick={()=>run(s)} className={button}><Check size={14}/>{s.replaceAll("_"," ")}</button>)}</> }
function EvidenceList({title,values}:{title:string;values:string[]}) { return values.length ? <div className="mt-4 text-sm"><strong>{title}:</strong> {values.join("; ")}</div>:null }
function DownloadButton({rfq,extension}:{rfq:{title:string;rendered_markdown:string};extension:string}) { return <button className={button} onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rfq.rendered_markdown],{type:"text/plain"}));a.download=`${rfq.title}.${extension}`;a.click();URL.revokeObjectURL(a.href)}}><Download size={14}/>{extension.toUpperCase()}</button> }

function PoeForm({id,initial,onSaved}:{id:string;initial?:Record<string,unknown>|null;onSaved:()=>void}) { const [form,setForm]=useState({niche_name:String(initial?.niche_name??""),search_volume:String(initial?.search_volume??""),search_volume_growth_percent:String(initial?.search_volume_growth_percent??""),conversion_rate_percent:String(initial?.conversion_rate_percent??""),observed_at:String(initial?.observed_at??"").slice(0,10),unmet_demand_notes:String(initial?.unmet_demand_notes??"")}); const save=useMutation({mutationFn:()=>api.savePoeEvidence(id,Object.fromEntries(Object.entries(form).map(([k,v])=>[k,["search_volume","search_volume_growth_percent","conversion_rate_percent"].includes(k)&&v?Number(v):v||null]))),onSuccess:onSaved}); return <Section title="03 / Product Opportunity Explorer evidence"><form onSubmit={(e)=>{e.preventDefault();save.mutate()}} className="grid gap-3 md:grid-cols-3"><input className={input} placeholder="Niche name" value={form.niche_name} onChange={e=>setForm({...form,niche_name:e.target.value})}/><input className={input} type="number" placeholder="Search volume" value={form.search_volume} onChange={e=>setForm({...form,search_volume:e.target.value})}/><input className={input} type="number" placeholder="Growth percent" value={form.search_volume_growth_percent} onChange={e=>setForm({...form,search_volume_growth_percent:e.target.value})}/><input className={input} type="number" placeholder="Conversion percent" value={form.conversion_rate_percent} onChange={e=>setForm({...form,conversion_rate_percent:e.target.value})}/><input className={input} type="date" aria-label="Observed date" value={form.observed_at} onChange={e=>setForm({...form,observed_at:e.target.value})}/><input className={input} placeholder="Unmet demand notes" value={form.unmet_demand_notes} onChange={e=>setForm({...form,unmet_demand_notes:e.target.value})}/><button className={button} disabled={save.isPending}>Save manual POE evidence</button></form></Section> }

function QuoteSection({id,quotes,onSaved}:{id:string;quotes:NonNullable<import("@/types/api").ValidationProject["quotes"]>;onSaved:()=>void}) { const suppliers=useQuery({queryKey:["suppliers"],queryFn:api.suppliers}); const [supplierId,setSupplierId]=useState(""); const [supplierName,setSupplierName]=useState(""); const [quantity,setQuantity]=useState("500"); const [unitPrice,setUnitPrice]=useState(""); const [moq,setMoq]=useState("500"); const [lead,setLead]=useState(""); const [sample,setSample]=useState(""); const save=useMutation({mutationFn:async()=>{let sid=supplierId;if(!sid){const s=await api.createSupplier({name:supplierName,platform:"other"});sid=s.id}return api.createValidationQuote(id,{supplier_id:sid,status:"received",moq:Number(moq),sample_cost:sample?Number(sample):null,production_lead_time_days:lead?Number(lead):null,tiers:[{quantity:Number(quantity),unit_price:Number(unitPrice)}]})},onSuccess:()=>{onSaved();suppliers.refetch();setUnitPrice("")}}); return <Section title="05 / Suppliers and quotes"><form onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate()}} className="grid gap-3 md:grid-cols-4"><select className={input} value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">New supplier</option>{suppliers.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{!supplierId?<input required className={input} placeholder="Supplier name" value={supplierName} onChange={e=>setSupplierName(e.target.value)}/>:<div/>}<input required className={input} type="number" placeholder="Quantity" value={quantity} onChange={e=>setQuantity(e.target.value)}/><input required className={input} type="number" step="0.01" placeholder="Unit price" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)}/><input className={input} type="number" placeholder="MOQ" value={moq} onChange={e=>setMoq(e.target.value)}/><input className={input} type="number" placeholder="Sample cost" value={sample} onChange={e=>setSample(e.target.value)}/><input className={input} type="number" placeholder="Lead time days" value={lead} onChange={e=>setLead(e.target.value)}/><button className={button} disabled={save.isPending}><Plus size={14}/>Add quote</button></form><p className="mt-3 text-xs text-terminal-amber">Manual estimate — verify freight, duty, tariff, inspection, and prep costs before ordering.</p><p className="mt-2 text-xs text-terminal-muted">{quotes.length} quote(s) recorded.</p></Section> }
function QuoteTable({quotes}:{quotes:NonNullable<import("@/types/api").ValidationProject["quotes"]>}) { const rows=quotes.flatMap(q=>q.tiers.map(t=>({q,t}))).sort((a,b)=>a.t.economics.landed_cost_per_unit-b.t.economics.landed_cost_per_unit); if(!rows.length)return <p className="text-sm text-terminal-muted">Add quote tiers to compare landed cost and margin.</p>; return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr>{["Supplier","Qty","Unit","Landed","MOQ","Sample","Lead","Margin","Ceiling","Status"].map(h=><th key={h} className="border-b border-terminal-line px-2 py-2 font-mono text-xs text-terminal-muted">{h}</th>)}</tr></thead><tbody>{rows.map(({q,t})=><tr key={t.id}><td className="px-2 py-2">{q.supplier.name}</td><td>{t.quantity}</td><td>{cash(t.unit_price)}</td><td>{cash(t.economics.landed_cost_per_unit)}</td><td>{q.moq??"—"}</td><td>{cash(q.sample_cost)}</td><td>{q.production_lead_time_days??"—"}</td><td>{t.economics.estimated_contribution_margin_percent==null?"—":`${t.economics.estimated_contribution_margin_percent.toFixed(1)}%`}</td><td>{t.economics.meets_cost_ceiling?"Yes":"No"}</td><td>{q.status}</td></tr>)}</tbody></table></div> }
const num=(v:number|null)=>v==null?"—":v.toFixed(1); const cash=(v:number|null)=>v==null?"—":`$${v.toFixed(2)}`;
